# Generated by Django 4.0.3 on 2022-03-05 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeofmedal', models.CharField(max_length=50)),
                ('yearofOlympics', models.IntegerField()),
            ],
        ),
    ]
