# Generated by Django 4.0.2 on 2022-03-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullnames', models.CharField(max_length=50)),
                ('medaltype', models.CharField(max_length=1000)),
            ],
        ),
    ]
